config/routes.rb
Rails.application.routes.draw do

resources :sources do
  resources :menu_items
end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  validates :item, presence: true, length: {minimum: 4}
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @menu_items = MenuItem.all
  end

  def new
    @menu_item = MenuItem.new
  end
  def create
    @menu_item = MenuItem.new(menu_items_params)

    if @menu_item.save
      redirect_to @menu_item
    else
      render :new
    end
  end

  def show
    @menu_item = MenuItem.find(params[:id])
  end


  def update
    @menu_item = MenuItem.find params[:id]

  if @menu_item.update menu_items_params
    redirect_to @menu_item
  else
    render :edit
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end
  def destroy
    @menu_item = Menuitem.find(params[:id])
    @menu_item.destroy
    redirect_to menu_path

  end


end

private
    def menu_items_params
      params.require(:menu_item).permit(:item, :description, :price)
    end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  def new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/home/index.html.erb
<h1>Welcome to City Wok!!</h1>
<h3>May I taka order prease</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for @menu_item do |f| %>
<% if @menu_item.errors.any? %>
  <div>
    <h2>
      Please fix the following errors:
    </h2>
    <ul>
      <% @menu_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :item %><br>
  <%= f.text_field :item %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.label :price %><br>
  <%= f.text_area :price %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Change Your Orda</h1>
<%= render 'form' %>

app/views/menu_items/index.html.erb
<h1>Our schitty food</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Description</th>
    <th>Price</th>
  </tr>

  <% @menu_items.each do |menu_item| %>
    <tr>
      <td><%=menu_item.item %></td>
      <td><%=menu_item.description %></td>
      <td><%=menu_item.price %></td>
      <td><%= link_to 'Show', menu_item_path(menu_item) %></td>
      <td><%= link_to 'Edit', edit_menu_item_path(menu_item[:id]) %></td>
      <td><%= link_to 'Delete', menu_item_path(menu_item), method: :delete, data: {confirm: 'are you sure'} %></td>
    </tr>
  <% end %>
</table>

app/views/menu_items/new.html.erb
<h1>Name yo schitty foods</h1>
<%= render 'form' %>

app/views/menu_items/show.html.erb
<p>
  <strong>Item</strong>
  <%= @menu_item.item %>
</p>
<p>
  <strong>Description</strong>
  <%= @menu_item.description %>
</p>
<p>
  <strong>Price</strong>
  <%= @menu_item.price %>
</p>

app/views/sources/new.html.erb
<h1>New menu</h1>
<%= form_for :source, url: sources_path do |f| %>
<p>
  <%= f.label :menu_title %><br>
  <%= f.text_field :menu_title %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>